<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>frontier_simulation</name>
  <version>0.0.0</version>
  <description>Simulation and visualization for frontier exploration.</description>

  <maintainer email="someones.mail.address@tuhh.de">Someones name</maintainer>
  <license>GPLv2</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>environment_map</depend>
  <depend>frontier_perception</depend>
  <depend>frontier_manager</depend>
  <depend>path_searching</depend>
  <depend>path_following</depend>
  <depend>eigen3_cmake_module</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
